
stages:
- install
- publish

cache:
  paths:
    - node_modules/

install:
  stage: install
  image: node:10.16.3
  script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm install

publish:
  stage: publish
  image: node:10.16.3
  script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm publish
  only:
  - master
